repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt
    - id: golangci-lint
    - id: go-vet
    - id: go-cyclo
      args: [-over=20]
    - id: no-go-testing
    - id: go-unit-tests
    - id: go-mod-tidy
    - id: go-build