version: "3.2"
services:

    redis:
      image: redis:alpine
      container_name: redis

    # grpc proxy
    grpc_proxy:
      build:
          context: ./game-integration/envoy_proxy
          args:
              envoy_base_id: 0
              envoy_config_file: ./envoy.local.yaml
      container_name: grpc_proxy
      image: grpc_proxy
      network_mode: "host" # linux needs network_mode but not ports
      # ports: # mac and wins need ports but not network_mode
        # - "8080:8080"
      volumes:  # need to setup certs folder with certeficate and private key
          - ~/.poker/certs:/certs

    dozzle:
      image: amir20/dozzle:latest
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
      ports:
          - 8080:8080